include:
- ./functions/bomharvesting-wimmera.py
kind: ArchiveUploadSpec
name: functions-bomharvesting-wimmera-py-WtT2

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bomharvesting-wimmera-128b7993-7b87-432f-818e-0c62f3a65f01
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-bomharvesting-wimmera-py-WtT2
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-11T15:21:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: bomharvesting-wimmera
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: bomharvesting-wimmera-128b7993-7b87-432f-818e-0c62f3a65f01
      namespace: ""
  requestsPerPod: 1
  resources: {}
