include:
- ./functions/bomharvesting-mallee.py
kind: ArchiveUploadSpec
name: functions-bomharvesting-mallee-py-kOja

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bomharvesting-mallee-db0042bc-24b0-4e2a-a915-f8b768e3ca8a
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-bomharvesting-mallee-py-kOja
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-11T15:20:40Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: bomharvesting-mallee
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: bomharvesting-mallee-db0042bc-24b0-4e2a-a915-f8b768e3ca8a
      namespace: ""
  requestsPerPod: 1
  resources: {}
