include:
- ./functions/crashprocessor.js
kind: ArchiveUploadSpec
name: functions-crashprocessor-js-Aiid

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: crashprocessor-6f699047-919a-4ba4-b4a8-fa3af1f48ea7
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-crashprocessor-js-Aiid
  environment:
    name: nodejs
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-15T04:00:53Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: crashprocessor
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodejs
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: crashprocessor-6f699047-919a-4ba4-b4a8-fa3af1f48ea7
      namespace: ""
  requestsPerPod: 1
  resources: {}
