include:
- ./functions/bomharvesting-south-west.py
kind: ArchiveUploadSpec
name: functions-bomharvesting-south-west-py-zE1n

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bomharvesting-south-west-87ef29c6-f5f5-4a3f-b469-590fab964003
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-bomharvesting-south-west-py-zE1n
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-11T15:09:21Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: bomharvesting-south-west
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: bomharvesting-south-west-87ef29c6-f5f5-4a3f-b469-590fab964003
      namespace: ""
  requestsPerPod: 1
  resources: {}
