include:
- ./functions/auharvesting.zip
kind: ArchiveUploadSpec
name: functions-auharvesting-zip-6Did

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: auharvesting
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-auharvesting-zip-6Did
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-13T05:20:22Z"
