include:
- ./getVolCrash.zip
kind: ArchiveUploadSpec
name: getvolcrash-zip-dKyB

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-vol-vs-crash
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: relapython
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://getvolcrash-zip-dKyB
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-13T10:23:12Z"
