include:
- ./functions/aucrimeharvesting.zip
kind: ArchiveUploadSpec
name: functions-aucrimeharvesting-zip-Ylzr

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: aucrimeharvesting
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-aucrimeharvesting-zip-Ylzr
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T02:41:45Z"
