include:
- ./functions/epaharvester.zip
kind: ArchiveUploadSpec
name: functions-epaharvester-zip-Midn

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: epaharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: bom-python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-epaharvester-zip-Midn
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-02T08:15:16Z"
