include:
- ./getVolEPA.zip
kind: ArchiveUploadSpec
name: getvolepa-zip-9qxd

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-vol-vs-epa
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: relapython
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://getvolepa-zip-9qxd
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-14T11:55:54Z"
