include:
- ./functions/population.zip
kind: ArchiveUploadSpec
name: functions-population-zip-Ynde

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: population
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-population-zip-Ynde
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T11:27:51Z"
