include:
- ./functions/aucrashharvesting.zip
kind: ArchiveUploadSpec
name: functions-aucrashharvesting-zip-SprN

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: aucrashharvesting
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-aucrashharvesting-zip-SprN
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T03:45:51Z"
