include:
- ./functions/traffic-analysis.zip
kind: ArchiveUploadSpec
name: functions-traffic-analysis-zip-eX0u

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: traffic-analysis
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39x
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-traffic-analysis-zip-eX0u
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T08:44:36Z"
