include:
- ./functions/auharvester.zip
kind: ArchiveUploadSpec
name: functions-auharvester-zip-FMWv

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: auharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: bom-python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-auharvester-zip-FMWv
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-05T07:03:57Z"
