include:
- ./functions/enqueue.zip
kind: ArchiveUploadSpec
name: functions-enqueue-zip-zSxx

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: enqueue
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-enqueue-zip-zSxx
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-11T12:41:16Z"
