include:
- ./functions/socialharvester.zip
kind: ArchiveUploadSpec
name: functions-socialharvester-zip-rQKy

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: socialharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-socialharvester-zip-rQKy
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T02:45:58Z"
