apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-vol-vs-crash
spec:
  createingress: true
  functionref:
    functionweights: null
    name: get-vol-vs-crash
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /traffic/vol-vs-crash/{type:[a-zA-Z0-9 ()]*}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /traffic/vol-vs-crash/{type:[a-zA-Z0-9 ()]*}
