apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-bom
spec:
  createingress: true
  functionref:
    functionweights: null
    name: get-bom
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: "*"
    path: /data/bom
    tls: ""
  method: ""
  methods:
    - GET
  prefix: ""
  relativeurl: /data/weather/bom
