apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-vol-vs-epa
spec:
  createingress: true
  functionref:
    functionweights: null
    name: get-vol-vs-epa
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: "*"
    path: /traffic/vol-vs-epa/{type:[a-zA-Z0-9.]*}
    tls: ""
  method: ""
  methods:
    - GET
  prefix: ""
  relativeurl: /traffic/vol-vs-epa/{type:[a-zA-Z0-9.]*}
