apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: bomharvesting-northern-country-ingest
spec:
  cron: '@hourly'
  functionref:
    functionweights: null
    name: bomharvesting-northern-country
    type: name
